### ISSUE TITLE
Incorrect time for some events

### ISSUE THREAD

**Issue by heytitle** [thangman22/techcal.dev#1]
Hi,

Thanks you very much for this awesome calendar. While browsing, I found that there was at least a event that its time isn't correct. I guess it's about the timezone.

<img width="1301" alt="Screenshot 2019-06-22 15 51 15" src="https://user-images.githubusercontent.com/1214890/59961727-d3a9b380-9505-11e9-9dae-db15065177ff.png">

**Comment by zkan** [comment]
FYI. It shows on the Google calendar correctly. 😱

<img width="379" alt="Screen Shot 2562-06-23 at 08 09 10" src="https://user-images.githubusercontent.com/704794/59970360-3e9ecd00-958e-11e9-91e7-045b6ec89bc4.png">

**Comment by thangman22** [comment]
Let's me check the wdiget

**Comment by thangman22** [comment]
Found it. Event Imported from Facebook is set to GMT timezone I fixed it

**Comment by zkan** [comment]
<3
